name: GitHub Actions Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    Deploy-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
            - run: git config --global user.name "github-actions"
            - run: npm i
            - run: npm run deploy
